### ISSUE TITLE
plan for GNNLux.jl

### ISSUE THREAD

**Issue by CarloLucibello** [JuliaGraphs/GraphNeuralNetworks.jl#461]
- [x] create the package #460 
- [ ] make it feature parity with GraphNeuralNetworks.jl (#469, #463, #475, #471)
    - [x] GNNChain
    - [x] GCNConv
    - [x] GraphConv 
    - [x] ChebConv
    - [x] AGNNConv
    - [x] CGConv
    - [x] EGNNConv
    - [x] EdgeConv
    - [x] GATConv
    - [x] GATv2Conv
    - [x] GatedGraphConv
    - [x] GINConv
    - [x] GMMConv
    - [x] MEGNetConv
    - [x] NNConv
    - [x] ResGatedGraphConv
    - [x] SAGEConv
    - [x] SGConv
    - [ ] TAGConv
    - [ ] TransformerConv
- [x] temporal convs (#470 )
- [ ] create documentation 
- [ ] Consider alternative names?
- [ ] register the package

cc @avik-pal

**Comment by asinghvi17** [comment]
@CarloLucibello sorry to ping here, but what's the status on GNNLux.jl these days?  Is it close to release / is there anything one could help with to move that over the finish line?

**Comment by CarloLucibello** [comment]
We are almost there, very few layers left. We need to add a docstring to each layer, adapting the ones from GraphNeuralNetworks.jl. If you want to help with that it would be great!

**Comment by asinghvi17** [comment]
Will give it a look this week!!
