### ISSUE TITLE
no version selector in the documentation pages

### ISSUE THREAD

**Issue by CarloLucibello** [JuliaGraphs/GraphNeuralNetworks.jl#536]

**Comment by aurorarossi** [comment]
they have version selector https://github.com/JuliaDynamics/DynamicalSystemsDocs.jl

**Comment by CarloLucibello** [comment]
the fix didn't work

**Comment by CarloLucibello** [comment]
For reference, other packeges using multidocumenter
https://github.com/FluxML/GeometricFlux.jl
https://github.com/JuliaAstro/EphemerisSources.jl
https://github.com/JuliaQUBO/QUBO.jl
https://github.com/JuliaAstro/GeneralAstrodynamics.jl
https://github.com/tecosaur/DataToolkit.jl

**Comment by CarloLucibello** [comment]
After #552, we have the version selector for each package but it is showing only the `dev` option. 
I don't know why this happens. 

The different versions are present in the branches `docs-gnngraphs`, `docs-gnnlib`, ..., where the single package docs are compiled, e.g.
https://github.com/JuliaGraphs/GraphNeuralNetworks.jl/tree/docs-gnngraphs

**Comment by CarloLucibello** [comment]
Now I see there has been a deployment problem from the gh-pages branch though
https://github.com/JuliaGraphs/GraphNeuralNetworks.jl/actions/runs/12227387246/job/34104044661
