### ISSUE TITLE
Stack Layers in a HeteroGraphConv Model

### ISSUE THREAD

**Issue by marthinkondjeni** [JuliaGraphs/GraphNeuralNetworks.jl#541]
How can do I stack a Dense layer or add more convolutional layers to the HeteroGraphConv layer in the code below?

```
using Flux

using GraphNeuralNetworks

using GNNGraphs

 g = rand_heterograph((:user => 10, :movie => 20), (:user, :rate, :movie) => 30)

x = (user = rand(Float32, 64, 10), movie = rand(Float32, 64, 20));

layer = HeteroGraphConv((:user, :rate, :movie) => GraphConv(64 => 32, relu))

y = layer(g, x)

```

**Comment by CarloLucibello** [comment]
probably you want to define a struct representing your model and the corresponding forward pass. See https://juliagraphs.org/GraphNeuralNetworks.jl/graphneuralnetworks/guides/models/#Explicit-modeling
