### ISSUE TITLE
the logo should blend in the background 

### ISSUE THREAD

**Issue by CarloLucibello** [JuliaGraphs/GraphNeuralNetworks.jl#558]
We should change the logo background or make it transparent

<img width="300" alt="Screenshot 2024-12-09 at 11 22 40" src="https://github.com/user-attachments/assets/4f6423e8-9498-4d20-9d6e-fd7b573e25fc">

**Comment by aurorarossi** [comment]
![image](https://github.com/user-attachments/assets/c3a6ec9e-8f88-45e2-9731-d8ebf179a15b)

I think this can be closed
